### ISSUE TITLE
Help column is hard to read

### ISSUE THREAD

**Issue by richardbrockie** [occipital/django-content-settings#115]
Hi,

Django==4.2.16
django-content-settings==0.23
python=3.11.10

The help column format makes it very narrow:
- Having several single value settings defined leads to a lot of wasted white space
- The help text is difficult to read in this layout
- Maybe the help text can be moved from a column to under the value field which gives much more horizontal space before the text wraps?

<img width="891" alt="image" src="https://github.com/user-attachments/assets/defbea3b-bd2d-46f3-86cf-f55669b5f99d">

**Comment by oduvan** [comment]
@richardbrockie I'll unite it with tags in the next version

**Comment by oduvan** [comment]
![image](https://github.com/user-attachments/assets/8b532970-cd06-45eb-b56e-ce01af95038a)

**Comment by oduvan** [comment]
update to `0.25`

**Comment by richardbrockie** [comment]
@oduvan Thanks - that's easier to read!
