### ISSUE TITLE
Django convention - use "help_text=" instead of "help="

### ISSUE THREAD

**Issue by richardbrockie** [occipital/django-content-settings#61]
The Django convention in model fields and other places is to use "help_text=", for example: https://docs.djangoproject.com/en/5.0/ref/models/fields/#help-text

My suggestion is that `django-content-settings` uses the same as Django has me well trained.

**Comment by oduvan** [comment]
That makes sense.

One more issue with help attribute, it actually acceps html, not text.

so the fix itself should include support only text, support both attributes and depreciation warning.

**Comment by oduvan** [comment]
thank you for the good catch

**Comment by richardbrockie** [comment]
> That makes sense.
> 
> One more issue with help attribute, it actually acceps html, not text.
> 
> so the fix itself should include support only text, support both attributes and depreciation warning.

Django `help_text=` accepts html - I use the occasional `<br />` for line breaks in long comments.

**Comment by oduvan** [comment]
will be released in 0.10.1
